import {
  Scale,
  LayoutDashboard,
  PlusCircle,
  ShieldCheck,
  Users,
  CheckCircle2,
  Clock3,
  AlertTriangle,
  UserCheck,
  Building2,
  Activity,
  ArrowRight,
  Menu,
  X,
  LogOut,
  RefreshCw,
  Search,
  ChevronRight,
  ChevronLeft,
  Eye,
  Pencil,
  UserPlus,
} from "lucide-react";
const icons = {
  Scale,
  LayoutDashboard,
  PlusCircle,
  ShieldCheck,
  Users,
  CheckCircle2,
  Clock3,
  AlertTriangle,
  UserCheck,
  Building2,
  Activity,
  ArrowRight,
  Menu,
  X,
  LogOut,
  RefreshCw,
  Search,
  ChevronRight,
  ChevronLeft,
  Eye,
  Pencil,
  UserPlus,
};
export default function Icon({ name, size = 20, ...props }) {
  const Component = icons[name] || Scale;
  return <Component size={size} aria-hidden="true" {...props} />;
}
